local builtin = require("telescope.builtin")
vim.keymap.set("n", "<leader>e", builtin.find_files, {})
vim.keymap.set("n", "<leader>gf", builtin.git_files, {})
vim.keymap.set("n", "<leader>lg", builtin.live_grep, {})
vim.keymap.set("n", "<leader>ff", builtin.quickfix, {})
vim.keymap.set("n", "<leader>p", builtin.builtin, {})
